digapp:
  build: dist
  ports:
    - "8080:8080"
  links:
    - mongo
  environment:
    EUI_SERVER_URL: 'http://192.168.59.103'
    EUI_SERVER_PORT: '80'
    IMAGE_SIM_URL: 'http://192.168.59.103'
    IMAGE_SIM_PORT: '80'
    EUI_SEARCH_INDEX: 'dig-latest'
    BLUR_IMAGES: 'false'
    MONGOHQ_URL: 'mongodb://mongo/dig'
    NODE_ENV: 'production'

nginx:
  image: dockerfile/nginx
  links:
    - digapp
  ports:
    - "80:80"
  volumes:
    - ./conf/nginx/.htpasswd:/etc/nginx/.htpasswd
    - ./conf/nginx_sites_enabled:/etc/nginx/sites-enabled
    - ./logs/nginx:/var/log/nginx

mongo:
  image: mongo